--- #YAML:1.0
name:               YAML-Accessor
version:            0.31
abstract:           A syntactical sugar wrapper for YAML::XS.
author:
    - Alex J. Avriette <alex@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:   0
    common::sense:     0
    Params::Validate:  0
    Scalar::Util:      0
    YAML::XS:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
